### ISSUE TITLE
ATP ADS: Javascript Error when running layout in construct 2

### ISSUE THREAD

**Issue by slaczky** [CocoonIO/cocoon-plugins-c2#1]
![1](https://cloud.githubusercontent.com/assets/2589102/8428651/81d56bc6-1f20-11e5-8415-a9a0ef89d4c5.png)
Uncaught refference error: Cocoon is not defined, when running in browser.

**Comment by LibelulaV** [comment]
Have you installed the plugins after exportation? 
https://github.com/CocoonIO/atomic-plugins-c2#ads-1
The missing file is injected by default when you install the plugins.

**Comment by slaczky** [comment]
I'm not exported the project, I just added the plugins to a construct 2 project, and pressed F5 buttont to test it.

**Comment by LibelulaV** [comment]
Without exportation, it will never work. You are using a C2 plugin that requires an additional installation after exportation, as it is written in the readme. 

If you want to test them, I recommend you to use the demo: https://github.com/CocoonIO/atomic-plugins-c2/tree/master/demos/ads
