### ISSUE TITLE
Legacy References in Social FB and Social GC plugins

### ISSUE THREAD

**Issue by ArcadEd** [CocoonIO/cocoon-plugins-c2#10]
**runtime.js in cocoon-fb**
line 242 reads:
self.runtime.trigger(cr.plugins_.**CJSAds**.prototype.cnds.onFacebookOpenAchievementsSuccess, self);

Should read:
self.runtime.trigger(cr.plugins_.**ATPFacebook**.prototype.cnds.onFacebookOpenAchievementsSuccess, self);

**runtime.js in cocoon-gc**
Line 216 reads:
self.runtime.trigger(cr.plugins_.**CJSAds**.prototype.cnds.onGCOpenAchievementsSuccess, self);

Should read:
self.runtime.trigger(cr.plugins_.**ATPGameCenter**.prototype.cnds.onGCOpenAchievementsSuccess, self);

Section starting at line 149 also does not include a isLoggedIn check, should it?

**Comment by keianhzo** [comment]
I fixed the bogus reference.

Thank you!
