### ISSUE TITLE
Cannot open c2 project.

### ISSUE THREAD

**Issue by uemasaharaki** [CocoonIO/cocoon-plugins-c2#12]
Hi, I've updated latest C2 and this plugin, but it cannot open C2 project. Thanks.

**Comment by AndreasReitberger** [comment]
Hi, 
please update this plugin.
https://github.com/ludei/Construct-2-plugin

You use the cocoonjs not the cocoonio plugin.

Regards
Andreas

**Comment by uemasaharaki** [comment]
@AndreasReitberger Thank you so much for your speedy reply! I'll try it.

**Comment by uemasaharaki** [comment]
@AndreasReitberger It works. Thank you!
