### ISSUE TITLE
CocoonAds reloads new ads every half second

### ISSUE THREAD

**Issue by elvisish** [CocoonIO/cocoon-plugins-c2#13]
I've found this sequence of events fixes the problem, but it still reloads the ads once when they are set from hidden to show:
1. Make a new blank layer on top and set it to active layer.
2. Use these conditions:
   Start of Layout >
                         Hide Banner Ad
                         Load a Banner Ad
                         Set banner layout
   Character Dies 
   Trigger Once >
                         Show the banner ad
   -----------------------------------------------------
   It's not ideal though, and as I said they still reload once whenever they show. I have a few examples of others having the same problem: https://www.scirra.com/forum/everyone-should-migrate-to-cocoon-io-asap-seriously_t167588?start=110 and https://forums.cocoon.io/t/ads-keep-changing-every-half-second/1588/3

**Comment by AndreasReitberger** [comment]
Hi,
I found the issue in the runtime.js file and submitted a Pull Request for it.
Thanks for letting me know!

Regards
Andy

**Comment by elvisish** [comment]
No problem! :D

**Comment by elvisish** [comment]
@AndreasReitberger  Is there a fix for the banner reloading after it's shown? I'm happy with the ads reloading of course, but it would look better if it did it before it shows it from being hidden.
