### ISSUE TITLE
Google Play achievement functions not functioning

### ISSUE THREAD

**Issue by nlbdotdev** [CocoonIO/cocoon-plugins-c2#15]
I've triple checked all my IDs and they are correct, and my leader-board is also working so I know the APP ID, linking, and login. is correct. Even the simple "show achievements" action does nothing. So I've come to the conclusion that is must be the plugin. Is anyone else having this issue?

**Comment by AndreasReitberger** [comment]
Hi,
The plugin works fine on my end. Can you please open a topic in the cocoon forum? (https://forums.cocoon.io) and share a screen shot or an example test case? Thank you!

**Comment by nlbdotdev** [comment]
I've posted the a topic [here](https://forums.cocoon.io/t/google-play-achievements-not-working-with-construct-2-coocoon-gpg-plugin/1737) but I'm not sure what else to post as I'm the only one with that google play access.
