### ISSUE TITLE
Construct 2 + Abmob =  not load not show ads

### ISSUE THREAD

**Issue by coldev** [CocoonIO/cocoon-plugins-c2#22]
run error windows 

[https://image.ibb.co/cXGz05/errror_ludei.jpg](https://image.ibb.co/cXGz05/errror_ludei.jpg)

[http://www.mediafire.com/file/8gvlf47209rrb7i/Downloads__const2_ludei_error.zip](http://www.mediafire.com/file/8gvlf47209rrb7i/Downloads__const2_ludei_error.zip)

android not load not show banners not intertials ads

thanks...

Contruct r244 + cocoon.io
Device android 4.4.2

**Comment by AndreasReitberger** [comment]
This is no issue, just add "System" -> "Is on platform -> cordova" whenever you are calling any cocoon function.
To test it you must run the game in the cocoon developer app or compile an app.

Regards 
Andy
