### ISSUE TITLE
blank screen when build

### ISSUE THREAD

**Issue by krestia** [CocoonIO/cocoon-plugins-c2#24]
hai. i have compile an apk. i made it with construct2 and build with cli. but when i add cocoon ads plugin, this apk only show blank screen. i've build it without this plugin and worked. i dont know why this plugin make my app blank screen. i have build with crosswalk, include cocoon canvas+, and nothing work. why?

**Comment by AndreasReitberger** [comment]
Hi,
whenever you are using a cocoon plugin in Construct 2, you also must add the counter part plugin at your cocoon project.
https://shatter-box.com/knowledgebase/cocoonio/#cocoonads

Best
Andy

**Comment by krestia** [comment]
Hi Andy, thanks for the link.
now its work fine. now i know that blankscreen is because i enabled minify script when export from construct2. i disabled it and work!

still i don't understand this ads is in test mode or not.

**Comment by AndreasReitberger** [comment]
Hi,
in order to test ads, just enter the Test ID's. You can find those IDs here.
https://shatter-box.com/knowledgebase/admob-how-to-test-ads/

Best,
Andy

**Comment by krestia** [comment]
Hi, thanks a lot.
now i can work with your suggestion.

**Comment by AndreasReitberger** [comment]
You're welcome, I'm glad to help you out :)
