### ISSUE TITLE
Google Play Games - Is logged in 

### ISSUE THREAD

**Issue by AndreasReitberger** [CocoonIO/cocoon-plugins-c2#4]
It isn't actually a bug, but it would be awesome to have the condition 'is logged in' for the Google Play Games and Game Center plugin!

Thanks a lot for your great plugins!

**Comment by AndreasReitberger** [comment]
Something new on that? It's been awhile since I've submitted this request..

Here is a screen shot from elmer_nancher.
![](https://standard-discourseorg.netdna-ssl.com/uploads/cocoon/original/1X/8eb4b74543e52c8b1174ee81ff3498cdc33d0afe.jpg)

https://forums.cocoon.io/t/we-need-cocoon-io-has-this-command-in-the-plugin-cocoon-googleplaygames/411

**Comment by keianhzo** [comment]
We have implemented this command. Install the latest version of the plugin and it shuld be there.
