### ISSUE TITLE
Google Play Games - Issue with 'Submit Achievement'

### ISSUE THREAD

**Issue by AndreasReitberger** [CocoonIO/cocoon-plugins-c2#5]
If I click on 'Submit Achievement' the 'Request Image' screen opens.

![image](https://cloud.githubusercontent.com/assets/2952443/9410599/625bf2b8-4821-11e5-8520-b412de431686.png)

Also the description is from the 'Request Image' action.

![image](https://cloud.githubusercontent.com/assets/2952443/9410607/69c5b5e8-4821-11e5-8c05-c442ff2c6eac.png)

Regards
Andreas

**Comment by Lucidical** [comment]
This seems to be fixed. I just did a test and everything worked ok.

Best regards

**Comment by AndreasReitberger** [comment]
I'll reload the plugins and let you know! Thank you :)

Regards
Andreas

**Comment by AndreasReitberger** [comment]
Sorry for the late respone, yes this issue is already fixed.
Thank you!
