### ISSUE TITLE
Typo in runtime js of cocoon-gc plugin.

### ISSUE THREAD

**Issue by DoubleSmith** [CocoonIO/cocoon-plugins-c2#6]
Hello, there is a typo in the cocoon-gc plugin which will crash the game on start up, if the plugin is active:
https://github.com/CocoonIO/cocoon-plugins-c2/blob/master/src/social/cocoon-gc/runtime.js
in line 65:
 Cnds.prototype.onGCGCGCLoginSuccess = function() {
        return true;
    };
    Cnds.prototype.onGCGCLoginFail = function() {
        return true;
    };

should be:

 Cnds.prototype.onGCLoginSuccess = function() {
        return true;
    };
    Cnds.prototype.onGCLoginFail = function() {
        return true;
    };

**Comment by LibelulaV** [comment]
Commit the changes and make a pull request :).

**Comment by DoubleSmith** [comment]
Ok, thanks i tried that.
I hope it worked, sorry i am not very familiar with git :)

2015-08-24 12:13 GMT+02:00 Marta Aguilera notifications@github.com:

> Commit the changes and make a pull request :).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CocoonIO/cocoon-plugins-c2/issues/6#issuecomment-134130330
> .

## 

_Reinhard Schmid_

_T_ +4369919447880
_E_ reinhard@doublesmith.com
_W_ http://www.doublesmith.com
- http://doublesmith.com/   https://www.facebook.com/doublesmith2013
  https://plus.google.com/u/0/+Doublesmith/posts
  https://twitter.com/DoubleSmith2013*
- http://doublesmith.com/*
