### ISSUE TITLE
CocoonAds: Uncaught TypeError: Cannot read property 'load' of undefined 

### ISSUE THREAD

**Issue by Aquabarbus** [CocoonIO/cocoon-plugins-c2#8]
In browser preview get error: "Uncaught TypeError: Cannot read property 'load' of undefined"

``` javascript
        Acts.prototype.LoadBanner = function() {
            this.bannerReady = false; 
            this.banner.load();
```
1. Create empty project
2. Add obj CocoonAds
3. Add Action Load Banner 
4. Run layout in browser preview

**Comment by Lucidical** [comment]
This is normal because the cocoon plugins don't work in a normal browser.
Use the CocoonCanvasplus plugin to prevent this(is canvas+).
Example:
![c2cio](https://cloud.githubusercontent.com/assets/7514355/10143657/ba90927a-6619-11e5-9885-05c4d0210fed.png)

**Comment by MichaelVParent** [comment]
I have a similar issue. and making sure to use CocoonCanvasplus before any attempt to load or display an ad doesn't help. The error message reads: "Unable to get property 'load' of undefined or null reference http://localhost:5000/ATPAds_plugin.js, line 228 (col 17)"

Please help. I can't test and make progress with my game.
